/*
   This page renders the content for the about splunk
   page. It contains the about splunk video that is played
   as the banner automatically. It also has a header and description
   for the checklist of required review items as well as the
   checklist itself
*/

// Import
import React, {Component} from 'react';
import splunkVideo from '../../images/splunk-intro.mp4';
import VideoBanner from '../VideoBanner/VideoBanner';
import ReviewChecklist from './ReviewChecklist';
import './AboutSplunkPage.css';

// This is the container for the content on the
// About Splunk Page
class AboutSplunkPage extends Component {
	// Render the video banner, header and directions, and checklist
	render() {
		return(
			<div>
				<VideoBanner 
					url={splunkVideo} 
					height="60%"
				/>
				<div className="container-fluid">
					<h3>Do you want to onboard your app's data to Splunk?</h3>
					<p>Machine data is generated by everything that powers your organization—including applications, infrastructure, 
					   security software and the Internet of Things. It’s complex and voluminous, growing at 50x the rate of traditional 
					   business data. And it contains valuable insights, if you’re able to make sense of it. That’s where Splunk
					   comes in! Uploading your data into Splunk will empower you to not only analyze historical data, but to predict
					   anomalies and stop them before they happen. Complete the checklist below to get started.</p>
					<ReviewChecklist store={this.props.store} />
				</div>
			</div>
		);
	}
}

export default AboutSplunkPage;
